### ISSUE TITLE
Monetary standards

### ISSUE THREAD

**Issue by AlexCatch** [langleyfoxall/technologies#104]
### What you would like to change/add
As the main type of system we develop here at Langley Foxall is enterprise level, we often have to deal with monetary values, handling these correctly is of the upmost importance when calculating things like costs & profits and it's very easy to get wrong (JS floating point precision anyone??).

### Why you would like to change/add this

It more of an issue in JS, where very interesting things can happen like so:

```javascript
var available = 600.90;
var cost = 200.30;
var total = cost * 3;

// Outputs: false
console.log(available >= total);

// Outputs: 600.9000000000001
console.log(total);
```

Two ways to get around this:

- Store monetary values as pence
- Store as decimals & use a library like [Dinero.js](https://sarahdayan.github.io/dinero.js/) for safe calculations.

I feel pence is the easiest & safest way to store monetary values unless you're dealing with ridiculous numbers (£1,000,000,000+)

But for 99% of use cases I say we make it a standard to use pence when storing & working with monetary values.

### Checklist
- [x] I have checked that this is not a duplicate issue.

### Sources

http://adripofjavascript.com/blog/drips/avoiding-problems-with-decimal-math-in-javascript.html
https://sarahdayan.github.io/dinero.js/
https://frontstuff.io/how-to-handle-monetary-values-in-javascript

👍 for storing sensible monetary values in pence
👎 for not

**Comment by dextermb** [comment]
They should be stored as the smallest value possible. As you suggested: pence.
