### ISSUE TITLE
Foreign keys/indexes in database definitions

### ISSUE THREAD

**Issue by wheatleyjj** [langleyfoxall/technologies#111]
### What you would like to change/add
We currently have a mismatch of preferences when it comes to how our databases are scaffolded.

We have the privilege of using the MySQL/InnoDB combination by default in Laravel development, which actually automatically indexes foreign keys (for all versions to current since at least 5.5), making the work required incredibly small.

I propose that we enforce the definition of foreign keys on all relations, and additionally if the system is not MySQL based - the addition of indexes if the engine/SQL version requires separate definition. I would say this could be done on a case-by-case but it's best to blanket add them IMO, even if only to match the behaviour of 99% of our systems (MySQL/InnoDB).

### Why you would like to change/add this
I've had to deal with a few projects now grinding to a halt after 6 months of usage by clients because the original database/migrations didn't include the usage of foreign keys/indexes.

Commercially this is extremely bad for us and causes businesses to literally not be able to work with the software that's running their business, they get frustrated at us - and it causes unnecessary, unscheduled maintenance where we have to drop what we're doing to deal with it.

This would include the use of the `ON DELETE` and `ON UPDATE` triggers on foreign keys, but I feel that that issue is slightly more controversial so will be handled separately. This issue ONLY relates to the definition of the FKs themselves.

### Examples
```
$table->unsignedInteger('user_id');
$table->foreign('user_id')->references('id')->on('users'); //onDelete('cascade');
```

### Checklist
- [x] I have checked that this is not a duplicate issue.

### Sources
https://dev.mysql.com/doc/refman/5.5/en/constraint-foreign-key.html
https://stackoverflow.com/questions/304317/does-mysql-index-foreign-key-columns-automatically

**Comment by ash123456789** [comment]
It's worth including the most common database servers along with whether they automatically index foreign keys. It could also be worth including a bit more documentation about our most commonly used database servers and certain quirks around them that could be useful to know.

* MariaDB - Automatically indexes foreign keys.
* PostgreSQL - Does NOT automatically index foreign keys.
* SQL Server - Does NOT automatically index foreign keys.
