### ISSUE TITLE
Update Git workflow to allow for assigned users to also merge pull requests

### ISSUE THREAD

**Issue by dextermb** [langleyfoxall/technologies#121]
### What you would like to change/add
Currently in our Git workflow we say that only the creator of the PR and repository admins should merge in pull requests. I'd like to propose allowing assignees to also merge pull requests.

### Why you would like to change/add this
As I've been working on support desk recently I've been assigning users to pull requests- for example: the reporter of the issue and myself. Obviously this only works if a pull request is made after resolving each individual task, but I find myself committing and opening PRs after every major change.

This way if the reporter reviews the pull request and sees that the issue is resolved then it can be merged in straight away rather than disrupting the person fixing issues.

I think doing this could also be useful in certain project situations as I'd use it to show who is in communication for a given task and has a better understanding of it than potentially other developers on the project.

### Examples
> If no one is assigned to the PR then only the person who created the pull request or admin should merge it. Even though it may of been accepted by the reviewers the person who created it might of noticed a change after the fact or admins might have a reason for delaying the merge.
>
> If other developers are assigned to the pull request then once approved it then anyone assigned can merge the pull request.

### Checklist
- [x] I have checked that this is not a duplicate issue.

**Comment by AlexCatch** [comment]
I don't see anything wrong with this request 👍

**Comment by wheatleyjj** [comment]
Actually a really good thought. Nice @dextermb .
