### ISSUE TITLE
CSS indentation/value alignment examples may be mixed up

### ISSUE THREAD

**Issue by jameswilddev** [langleyfoxall/technologies#125]
### What you would like to change/add
On the [CSS standards page](https://github.com/langleyfoxall/technologies/blob/master/styleguides/stylesheets/core.md#general-standards):
- "Everything should be indented using 4 spaces":
  "good" aligns values, while "bad" does not.
- "Property values should be aligned by value":
  Both "good" and "bad" align property values; they only differ in that "bad" uses two space indentation, while "good" uses four space indentation.

### Why you would like to change/add this

Examples do not match what they are demonstrating.

### Examples

N/A

### Checklist
- [x] I have checked that this is not a duplicate issue.

### Sources

N/A

**Comment by AlexCatch** [comment]
I think it's to demonstrate bad examples vs good examples - that's why the bad example is indented with 2 spaces ( which is wrong ) and the good example is intended with 4 ( which is correct ).

Maybe not indenting at all for the bad examples would make it more clear?

**Comment by jameswilddev** [comment]
Sorry, should have been clearer; both the "good" and "bad" examples for "Property values should be aligned by value" align by value.

This is pretty straightforward to raise a pull request for so I'll get on that in downtime.

**Comment by DivineOmega** [comment]
Fixed by #126.
