### ISSUE TITLE
Global gitignores

### ISSUE THREAD

**Issue by dextermb** [langleyfoxall/technologies#14]
Recently I came across some documentation through GitHub about [global ignore](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore)s.

* David walsh has also [posted about it](https://davidwalsh.name/global-gitignore)
* A stackoverflow [answer](https://stackoverflow.com/a/16780799/8176262) shows that it could be easy to set up

Files/Directories that we could put in here could be:
* `node_modules/`
* `vendor/`
* `.env`
* `.DS_Store`

and even IDE specific things:
* `.idea/` for JetBrains software
* `.vscode/` for Visual Code

This would make it so that we do not forget to add them at a project level. Perhaps documentation should be written on it after some testing?

**Comment by wheatleyjj** [comment]
This is already in the .gitignore file - although there is an issue with it displaying through the domain...
