### ISSUE TITLE
Pull Request and Issue templates

### ISSUE THREAD

**Issue by ash123456789** [langleyfoxall/technologies#15]
Since we are moving more towards Pull Requests and using GitHub issues, would it be worth enforcing an issue / pull request template across repositories to make understanding of issues and pull requests easier? If a template is enforced, when someone creates an issue or pull request it will automatically popular the input with the template.

I have used it on GoEffortless when Jake was QAing and it made understanding the issue significantly easier and sped up the process since Jake could fill out the small form and I could then only read what sections I needed to read. Rather than reading a whole paragraph that may not contain information I'm looking for. Example of a markdown issue template below for those of you that don't have GE repository access.

Some great examples of templates here: https://github.com/stevemao/github-issue-templates
CakePHP use it extensively and it's quite useful for them: https://github.com/cakephp/cakephp/issues

What are your thoughts?

---

**Page URL / Endpoint**:
**Request Type**:

* [ ] UI
* [ ] UX
* [x] Functionality
* [ ] Validation
* [ ] Database Error

### Section
* [ ] Customer Portal
* [ ] Admin Panel
* [ ] API

### What you did
EXPLAIN WHAT YOU DID, PREFERABLY WITH CODE EXAMPLES, HERE.

### What happened
EXPLAIN WHAT IS ACTUALLY HAPPENING, HERE.

### What you expected to happen
EXPLAIN WHAT IS TO BE EXPECTED, HERE.

### Images (if needed)
IMAGES HERE.

**Comment by dextermb** [comment]
_Recently_ GitHub also made it so there can be many templates for issues, when clicking create issue you're shown a list of templates. I'm trying to find a repo where I saw it being used.

**Comment by dextermb** [comment]
Here's some posts by GitHub on the topic:
* [Multiple issue and pull request templates](https://blog.github.com/2018-01-25-multiple-issue-and-pull-request-templates/)
* [Issue template improvements](https://blog.github.com/2018-05-02-issue-template-improvements/)

**Comment by AlexCatch** [comment]
I think we also need to decide what we are going to actually use for issue management etc as right now we're using a mixture of Jira & Github.

**Comment by dextermb** [comment]
You can also put comments within markdown, from what I've seen using HTML comment syntax `<!-- -->` which could be useful to add optional sections or general information in a template without it being displayed when an issue is created.

**Comment by dextermb** [comment]
I believe this can be closed

PR Reference #64
