### ISSUE TITLE
JS standards

### ISSUE THREAD

**Issue by AlexCatch** [langleyfoxall/technologies#23]
We're at a point where we need some internal JS standards to accompany the PHP standards we've got in place.

Standards in JS are a lot easier to manage with tools like Eslint so I think that's where we should start. I've been using a modified version of the Airbnb javascript style guide for a few months now.

https://github.com/airbnb/javascript

Top level standards would essentially involve ensuring that ESLint passes when given your project's source.

I'd love opinions on this - @dextermb @DivineOmega @NilesB @wheatleyjj

**Comment by dextermb** [comment]
Any linting be it JavaScript or PHP would be great. ESLint is independent of an IDE, which would make it easier for people to use without losing their IDE of choice.

As most of our projects are Laravel based, with Blade, I think we should focus on getting people to standardizing PHP first. I doubt people are following PSR standards yet even though we had an open discussion on it.
