### ISSUE TITLE
PHP Standards: Abbreviated variable names

### ISSUE THREAD

**Issue by ash123456789** [langleyfoxall/technologies#27]
After reading some of the code in GoEffortless I realised that a there are number of instances where the variable names have been overly abbreviated, e.g. `quoteOrder` would become `qO` & `energyUsage` would become `eU`.

I believe that this will confuse people that could potentially be jumping on the project to bug fix or add additional functionality. This could also spread into other projects so I think defining a standard internally would be ideal to prevent future confusion - just like it confused me when looking at it just.

What are your thoughts?

**Comment by AlexCatch** [comment]
Variable should nearly always explain what they are, don't be afraid of long variable names.

The only real exception for abbreviating variable names should be inside of loops but even them I'm hesitant.

**Comment by dextermb** [comment]
[Self documenting code](https://en.wikipedia.org/wiki/Self-documenting_code).

**Comment by DivineOmega** [comment]
Agree with all of this. There's no need to avoid long tail variable names.

**Comment by wheatleyjj** [comment]
Good issue Ash. 

Question is - do we extend this to a general programming practices page or highlight this at a lower level?

**Comment by DivineOmega** [comment]
@wheatleyjj I agree with placing this on a general programming practices page. It is the kind of point that applies to all languages.
