### ISSUE TITLE
Update master branch name to develop

### ISSUE THREAD

**Issue by AlexCatch** [langleyfoxall/technologies#32]
I feel like if we're going to be using `master` as a development branch, we don't lose anything by being  clear and renaming `master` to `develop`.

The word `master` can be very confusing when we have multiple devs who come from different git workflows where `master` can mean production in one or development in another.

Opinions on this would be great 👍 

@DivineOmega @dextermb @wheatleyjj @NilesB

**Comment by wheatleyjj** [comment]
I see both sides to this, to the point that I'm impartial.

Happy for a thumbs up/down situation - go away and do your research :)

👍 THUMBS UP TO PASS MOTION 
👎 THUMBS DOWN TO REJECT MOTION

**Comment by DivineOmega** [comment]
I'm uncertain, so this comment is mostly me playing devil's advocate.

On one hand, the intent of `develop` is far clearer than `master`. It's only a name, and changing it would make it immediately obvious what `develop` is for, assuming we still keep it set a the main/default branch for the repo.

On the other hand, the existence of a `production` branch, assuming it is noticed, rules out most confusion over whether `master` is a unstable branch. The unstable `master` branch is also a very common convention on GitHub, especially amongst open source projects.

Another possible consideration is whether any continuous integration makes assumes about the `master` branch being unstable. To my knowledge, I can not think of any CI solutions that make these assumptions, but I tend to make `master` my unstable branch, so I don't have experience testing this possibility.

**Comment by AlexCatch** [comment]
@DivineOmega as far as I'm aware, no CI would have a default build be on master, it's either build on every push to every branch or you specifically limit the branches that can trigger a build on push.

**Comment by DivineOmega** [comment]
@AlexCatch It's been the same in my experience too.

**Comment by wheatleyjj** [comment]
@ash123456789 we need to remember to tag all contributors in these.

**Comment by DivineOmega** [comment]
Votes needed on this issue! :slightly_smiling_face: 

@robmilward @blue-axolotl @JacobBrassington @markwaynejones @JamesLF @MaxHarrisonGit @NilesB
