### ISSUE TITLE
Should technical tests be part of the technologies repo?

### ISSUE THREAD

**Issue by AlexCatch** [langleyfoxall/technologies#36]
We're in the process of creating a few technical tests for potential new hires to ensure the technical ability of the candidate is at the level we expect.

Is this something that should reside in it's own repo `langleyfoxall/tech-tests` or inside this repo at the top level?

@DivineOmega @wheatleyjj @NilesB @ash123456789 @dextermb

**Comment by wheatleyjj** [comment]
I think separately.

I was thinking about this the other day and it would be great if users could take and submit technical tests based upon their experience. At the moment we make have one generalised form - I'd like users to be able to take as many tests as they like and answer questions to help us build the BEST picture of the candidates.

**Comment by AlexCatch** [comment]
Maybe a small web app for this would be cool.

`candidates.langleyfoxall.co.uk`

Login to the web app, view your outstanding tests, view specs and then mark as completed etc after completing etc

Might be over kill would be a very nice addition.

**Comment by DivineOmega** [comment]
@wheatleyjj Definitely a great idea regarding candidates being able to select and fill in as many tests as they like.

**Comment by dextermb** [comment]
Don't forget we have `langleyfoxall.app`

**Comment by DivineOmega** [comment]
Closing this issue, as technical tests have already been created within the main Langley Foxall website repo.
