### ISSUE TITLE
Method names for general CRUD in controllers

### ISSUE THREAD

**Issue by ash123456789** [langleyfoxall/technologies#38]
After having a good discussion within ELM chat about method names for general CRUD as well as resource controllers, we still haven't come to agreement on the issue so we thought it would be a good discussion to have for this repository and so we could potentially standardise it internally.

**Resource controllers**
Laravel allows you to generate resource controllers so that there is a standard structure for the general CRUD for both the Web and potentially API portions of your application, `php artisan make:controller Name --resource`. Documentation for resource controllers is [here](https://laravel.com/docs/5.7/controllers#resource-controllers).

Once you have generated the resource controller you can then use a single line within your routing file - `Route::resource('name', 'NameController');` - to map the routes for you without you having to type them all.

**The issue**
Alex believes that names on the method should be more clear, e.g. `create` does not represent what it actually does (which is render the view to store an entity), and believes it should have a more clear name like `showCreateView`

**Alex's perspective**
You have two functions, `store` & `create`, the `store` function is actually used to create the entity but the `create` function is used to render a view, in my opinion the `create` function doesn't accurately represent what the function is doing, which is rendering the view.

**Ash's perspective**
The Laravel documentation states that `create` should render the view and `store` should save the entity, that is only for the `web` side of your application. If you are using the `api` side of your application, resource controllers are still valid however you would have no need for the `create` and `edit` methods - which are typically used to render the view.

I believe we should stick to the documentation so that it is standard instead of moving away from that portion of the documentation. Everyone above Intermediate level, and potentially Junior level, that uses resource controllers should understand the names and what they actually do. Along with this, when you generate PHPDocs for methods it clearly states what it will return when you look at the `@return` parameter.

If the method returns a view it will show `@return \Illuminate\Contracts\View\Factory|\Illuminate\View\View`, which clearly tells developers what the method will return.

**Comment by NilesB** [comment]
I'm with the Laravel documentation and Ash on this one. Creating a resource is done by the user in the view by entering the data, when the data is sent to the server nothing is being created, it is simply being stored in a database.

**Comment by DivineOmega** [comment]
I am for using resource controllers as is. They're a standard within Laravel that can save quite a bit of time written out CRUD routes. Another major benefits is they enforce a consistent structure to CRUD route URLs and names, controllers and (admittedly non-obvious) method names.

The method names however, are documented in Laravel's official documentation. Also, each generated resource controller comes with automatic comments explaining the method's function.

See this example resource controller from Olympian, where we've used them extensively. Notice that method contents and extraneous methods have been snipped for brevity. 

```php
class CustomerController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        /** snipped **/
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        /** snipped **/
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CustomerStoreRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(CustomerStoreRequest $request)
    {
        /** snipped **/
    }

    /**
     * Display the specified resource.
     *
     * @param User $customer
     * @return void
     */
    public function show(User $customer)
    {
        /** snipped **/
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param User $customer
     * @param CustomerBaseRequest $request
     * @return \Illuminate\Http\Response
     */
    public function edit(User $customer, CustomerBaseRequest $request)
    {
        /** snipped **/
    }

    /**
     * Update the specified resource in storage.
     *
     * @param CustomerUpdateRequest $request
     * @param User $customer
     * @return \Illuminate\Http\Response
     */
    public function update(CustomerUpdateRequest $request, User $customer)
    {
        /** snipped **/
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param CustomerDestroyRequest $request
     * @param User $customer
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(CustomerBaseRequest $request, User $customer)
    {
        /** snipped **/
    }
```

**Comment by AlexCatch** [comment]
Okay then, I'm happy with sticking as is.
