### ISSUE TITLE
No reference to the site anywhere obvious

### ISSUE THREAD

**Issue by AlexCatch** [langleyfoxall/technologies#40]
The link to the Github pages site is not shown anywhere obvious in the repo, it would make sense to have it in the tagline or somewhere near the top of the `README.md`

**Comment by dextermb** [comment]
*`README.md`

But yeah, probably should be somewhere. There is a `URL` field for repos that shows above the repo breakdown, below the title

**Comment by DivineOmega** [comment]
@dextermb Good idea to put it in there.

We could also put it in the README, and then use CSS to hide the link from the GitHub pages site.

**Comment by AlexCatch** [comment]
@wheatleyjj has sorted this.

**Comment by DivineOmega** [comment]
Nice!
