### ISSUE TITLE
Git flow: Add improvement

### ISSUE THREAD

**Issue by ash123456789** [langleyfoxall/technologies#41]
Currently we have no branch structure to handle improvements to existing features, features that are not broken and aren't a new feature.

Should we have a branch structure for improvements? E.g. `improvement/*`

One thing Jordan noted when I was discussing this with him was that it may add a little bit more complexity to our existing Git flow structure.

**Comment by dextermb** [comment]
Sure. Seems like a good Idea, it could be used in the yfb node repo as that won't really be any new features but improvements.

**Comment by DivineOmega** [comment]
I suggested `feature/feature-i-am-working-on/specific-improvement-i-am-making` as possible branch names.

**Comment by dextermb** [comment]
@DivineOmega I've also done this previously. Such as when I was doing JWT stuff for YFB iirc
