### ISSUE TITLE
Open source packages page(s)

### ISSUE THREAD

**Issue by DivineOmega** [langleyfoxall/technologies#47]
What are people's thoughts about us putting together a page where we could add curated, useful open source packages? Alternatively, it could be done on a page per platform basis.

**Comment by wheatleyjj** [comment]
I like the sound of a centralised page for all of them. Fragmenting them doesn't make too much sense and would only remove visibility for packages on other platforms.

**Comment by ash123456789** [comment]
Potentially, however this functionality is partially implemented for the developer centre. Unsure if @wheatleyjj would like to move this to a page into tech repo.

**Comment by AlexCatch** [comment]
I feel like it would be reinventing the wheel as those lists already exist in their hundreads. Maybe cherry picking some links from here would be easier & take less time?

https://github.com/sindresorhus/awesome

**Comment by NilesB** [comment]
On the React Native documentation I have recommended packages as well as blacklisted ones that we have had bad experiences with in the past. I like the idea of having them on different platforms.

**Comment by wheatleyjj** [comment]
@NilesB I think per platform for stuff that isn't ours, but centralised pages for our packages would help exposure.

**Comment by NilesB** [comment]
@wheatleyjj absolutely

**Comment by dextermb** [comment]
I believe this can be closed

PR Reference #71
