### ISSUE TITLE
Spacing changes to files

### ISSUE THREAD

**Issue by wheatleyjj** [langleyfoxall/technologies#48]
I've hit an issue in PR's where someone was using the wrong space count in a file, so someone used the old `option` + `cmd` + `l` to re-space everything.

This made picking up the actual changes to those files very difficult to pick up and review.

We should potentially note this down for people to separately submit spacing changes?

**Comment by dextermb** [comment]
@NilesB, although this makes it easier for reviewers people should still stick to a standard

**Comment by AlexCatch** [comment]
@dextermb I agree, spaces should be handled by a standard.
