### ISSUE TITLE
Defining constants

### ISSUE THREAD

**Issue by dextermb** [langleyfoxall/technologies#5]
When it comes to constants, for example at the top of a class, I generally do something like this:
```
class Request {
    const BASE_URI = 'http://langleyfoxall.co.uk';

    // ..
}
```

But we have come to an agreement on using `camelCase` for variables. I'd like to exclude constants from this. I think that all constants should be uppercase.

```
const base_uri = 'http://langleyfoxall.co.uk';
```
```
const baseURI = 'http://langleyfoxall.co.uk';
```

```
const BASEURI = 'http://langleyfoxall.co.uk';
```

Thoughts? This is probably something for the discussion on Friday.

cc @wheatleyjj @AlexCatch @DivineOmega

**Comment by DivineOmega** [comment]
It's worth noting that PHP example documentation and the survey used for creating PSR-2 recommends `CAPITALS_WITH_UNDERSCORES` for constants as the standard styling.

However, constants within classes are always referenced by `self::MY_CONSTANT` or `self::myConstant`, so it is reasonably easy to identify them in code. This syntax is only the same as access to static member variables.

I'm not too fussed either way.

**Comment by dextermb** [comment]
@DivineOmega That's great then. Everything so far, apart from `camelCase` variables, I was already doing (unknown to me as PSR spec).

As we're following PSR I believe this thread is resolved then.

**Comment by AlexCatch** [comment]
I believe strongly that the format for constants should be ```VARIABLE_NAME```.
