### ISSUE TITLE
PHP Standards: Opening braces for methods

### ISSUE THREAD

**Issue by ash123456789** [langleyfoxall/technologies#50]
Currently the PHP standards within this repository state the following.

```
Opening braces for methods MUST be on the same line as the declaration, and closing braces MUST go on the next line after the body.
```

Which means the methods look like this:

```php
    public function example() {
        if ($bool) {
            //
        }
    }
```

I think this should be changed to match PSR-2, which states:

```
Opening braces for methods MUST go on the next line, and closing braces MUST
go on the next line after the body.
```

There's also a few other reason this should be changed:

* The current standard we have makes it slightly more difficult to read the body of the method.
* Almost every other repository I have seen on GitHub/Bitbucket/etc. has the opening brace on the next line after the declaration.
* PSR-2 already has this defined and I believe what PSR-2 has defined is perfectly fine.
* Almost every PHP framework I have seen (e.g. Laravel, CakePHP) has the opening brace on the next line.
* I have had instances where PHPStorm has forced the opening brace on a new line after running my code through its autofix/autocompletion.
* Other people in the office prior to these PHP standards have put the opening brace on the new line.

If we follow PSR-2 it means the method structure would look like this, which I believe makes the body much easier to read.

```php
    public function example() 
    {
        if ($bool) {
            //
        }
    }
```

**Comment by wheatleyjj** [comment]
I think when initially raised the majority preferred on the same line, hence it got added.

Of course things may have changed - thumbs up or down on @ash123456789 's issue :)

**Comment by AlexCatch** [comment]
`The current standard we have makes it slightly more difficult to read the body of the method.`
I don't see this at all.

`Almost every other repository I have seen on GitHub/Bitbucket/etc. has the opening brace on the next line after the declaration.`
That's fine but we did all agree on having the brace on the same line to match how we work in other languages.

`I have had instances where PHPStorm has forced the opening brace on a new line after running my code through its autofix/autocompletion.`
This can be tweaked in PHPStorm preferneces

`Other people in the office prior to these PHP standards have put the opening brace on the new line.`
I've yet to see this.

**Comment by dextermb** [comment]
I prefer to follow PSR-2 as that's just what I've always done. Logical statements are on the same line, for example `if` or `switch` whereas `class`, `function` are on separate lines.

**Comment by ash123456789** [comment]
> `Almost every other repository I have seen on GitHub/Bitbucket/etc. has the opening brace on the next line after the declaration.`
> That's fine but we did all agree on having the brace on the same line to match how we work in other languages.

I don't believe I was a contributor to this repository back when the PHP standards were defined. I only really joined in after the Cloudflare documentation was made and started being more active so I wasn't involved in the discussion surrounding the PHP standards. 

This is simply highlighting a potential issue that people can voice their opinion on and whether they would actually like to change it - which there is absolutely no harm in doing regardless of what the topic is or whether it has been agreed on prior. Opinions change over time.

> `I have had instances where PHPStorm has forced the opening brace on a new line after running my code through its autofix/autocompletion.`
> This can be tweaked in PHPStorm preferences

It should not have to be changed since PHPStorm by default follows the PSR standards.

> `Other people in the office prior to these PHP standards have put the opening brace on the new line.`
> I've yet to see this.

Look at every single generated class in Laravel that people in this office have made. Look at Olympian, GoEffortless, Sunfield, as well as other projects that I don't have access to.

**Comment by wheatleyjj** [comment]
I think it's going to be a real struggle if we try and change opinions of people in this headstrong group as we will just have back and forth all day. 

I suggest we just do our research and vote.

**Comment by DivineOmega** [comment]
I also believe we should follow PSR-2 regarding this.

**Comment by AlexCatch** [comment]
Well I guess it's settled then, makes me feel slightly sick but oh well 😷

**Comment by wheatleyjj** [comment]
I presume that we shouldn't close the issue until it's been resolved?

**Comment by AlexCatch** [comment]
I was under the impression this was just a poll issue and that another one would be opened to actually move forward with a PR, if we're going to reference this issue in the relevant PR it makes sense to keep it open 👍
