### ISSUE TITLE
HTML Element spacing and new lines

### ISSUE THREAD

**Issue by MaxHarrisonGit** [langleyfoxall/technologies#62]
HTML spacing and new lines.
if you have an element that looks like the following:
```
<a 
        style="display:inline-block;" alt="Big A"
/>
```
The spacing should instead look like

`<a style="display:inline-block;" alt="Big A" />`

--
However there is a caveat for this, if your line is exceeding 140 chars, then you should start a new line for that element and indent on that new line.

**Comment by dextermb** [comment]
This is the example code @MaxHarrisonGit is mentioning:
```html
<div
    style="display:block;background:#1e293d;padding:20px 20px 10px;text-align:center;"
>
    <a 
        style="display:inline-block;" alt="Colossus Bets Sponsor"
        href="https://www.colossusbets.com/pools/list/sports?registration=true&cb_ref_code=YOURFREEBET&utm_source=YFB&utm_medium=Website&utm_campaign=Header&utm_content=Header"
    >
        <img
            src="/images/colossus-bets.gif"
        />
    </a>
</div>
```

I had broken up attributes onto new lines to help Fraser understand the code while I was explaining it to him.

While it is not needed when someone understands the code, it definitely makes it easier to read. Not to mention that having attributes on separate lines is pretty much the go to when writing in React, so we will have to add an exception clause in there for this.

Inline styling is something that I always find interesting. If there's only one occurrence of an element (and there's no plans for it to be used multiple times) then I don't see an issue with it.

**Comment by MaxHarrisonGit** [comment]
Not saying split it in the middle of a href if you got a href, put a line break infront of the href, so that starts on a new line, maximise the spacing efficiency, this will make it clearer to read and not take up a ridiculous amount of lines.

**Comment by AlexCatch** [comment]
We don't have a style guide for html yet so no one can say what is right and what is wrong.

**Comment by MaxHarrisonGit** [comment]
I am not saying it doesn't help it easier to read, and I am not saying not to help fraser, however, before pushing this up it should be changed to correct way.

and you should not make a new line for each attribute inside a element on react, otherwise a single div with a few attributes inside that at most could take up two lines would be taking upto 10 lines, which is then making it hard to read.

**Comment by dextermb** [comment]
> We don't have a style guide for html yet so no one can say what is right and what is wrong.

**Comment by MaxHarrisonGit** [comment]
I never said I was Right Dexter, This is my opinion. I might be wrong, But if we don't put our ideas and thoughts forward we wont get anywhere.

**Comment by dextermb** [comment]
I will take the opportunity to push forward something though:

> If we do write a styleguide for multiline HTML tags and attributes then they should follow this standard:
> ```
> <img
>     id="<an id>"
>     class="<a class>"
>     src="<a src>"
> />
> ```
> 
> Rather than:
> ```
> <img id="<an id>"
>     class="<a class>"
>     src="<a src>"
> />
> ```

**Comment by dextermb** [comment]
> I never said I was Right Dexter, This is my opinion. I might be wrong, But if we don't put our ideas and thoughts forward we wont get anywhere.

But you have used "correct way" and such, meaning you think your way is right? 😆

**Comment by AlexCatch** [comment]
We'll revisit this at a later stage.

**Comment by dextermb** [comment]
We should put forward some HTML standards. Both for JavaScript frameworks (JSX) and standard HTML.

**Comment by MaxHarrisonGit** [comment]
> > I never said I was Right Dexter, This is my opinion. I might be wrong, But if we don't put our ideas and thoughts forward we wont get anywhere.
> 
> But you have used "correct way" and such, meaning you think your way is right? 😆

Well yes, I think I am right? otherwise I wouldn't of made the Issue? I am confused, do you think i would create and Issue that I thought I was wrong on?
