### ISSUE TITLE
Middleware casing

### ISSUE THREAD

**Issue by wheatleyjj** [langleyfoxall/technologies#66]
### What you would like to change/add
I propose that we standardise the naming convention on our middleware. 

My personal preference would be to match Laravel with lowercase/kebab-case

### Why you would like to change/add this
I'd like to change this after seeing non-standardisation in a PR where each of the middleware was using a different, non-standard convention.

### Examples
This is what scarred me:
 ```
        Route::middleware(['adminForcePasswordChange'])->group(function () use ($adminRouter) {
             Route::middleware(['UserReadOnly'])->group(function () use ($adminRouter){
```

This is what I'd like to see:
 ```
       // Whether the middleware should be named this is a different conversation
        Route::middleware(['admin-force-password-change'])->group(function () use ($adminRouter) {
             Route::middleware(['user-read-only'])->group(function () use ($adminRouter){
```

### Checklist
- [x] I have checked that this is not a duplicate issue.

### Sources
[Laravel's Existing Middleware](https://github.com/laravel/laravel/blob/master/app/Http/Kernel.php#L54)

##### PS - should this start a "Laravel Standards" document?

**Comment by NilesB** [comment]
In the case of `admin-force-password-change` I prefer something like `admin.force-password-change` and all `admin` related middleware are prefixed with `admin`.

**Comment by wheatleyjj** [comment]
@NilesB That would follow Laravel more closely. Good Addition

**Comment by dextermb** [comment]
@NilesB I agree that a prefix should be a `.` as shown in Laravel's default middleware, but as for naming general middleware it should be `kebab-case`.

**Comment by AlexCatch** [comment]
@NilesB I think that's a good idea as long as there is more than one middleware in that 'namespace' otherwise it's just unnecessary grouping.

**Comment by DivineOmega** [comment]
I agreed with all of this. Definitely `kebab-case`.
