### ISSUE TITLE
No space before/after Square bracket

### ISSUE THREAD

**Issue by MaxHarrisonGit** [langleyfoxall/technologies#72]
### What you would like to change/add
I propose that we use no spaces at the start and the end of Square Brackets.

### Why you would like to change/add this
In my opinion, because it is interacting with the object/variable to the left of the square brackets, it shouldn't have a space to clearly show that is it is all in part with that object/variable. 

### Examples
This:
```php
$data[$key]
```
Not:
```php
$data[ $key ]
```

This:
```php
$form->is_form_visible_customer = isset($data['is_form_visible_customer']) ? ($data['is_form_visible_customer'] == 'on' ? 1 : 0) : 0;
```
Not:
```php
$form->is_form_visible_customer = isset($data[ 'is_form_visible_customer' ]) ? ($data[ 'is_form_visible_customer' ] == 'on' ? 1 : 0) : 0;
```

### Checklist
- [x] I have checked that this is not a duplicate issue.

* [Langley Foxall](https://langleyfoxall.co.uk) - The Langley Foxall website

**Comment by AlexCatch** [comment]
I agree with this

**Comment by DivineOmega** [comment]
Agreed.

**Comment by dextermb** [comment]
I agree, but you should totally look at (markdown code blocks)(https://help.github.com/articles/creating-and-highlighting-code-blocks/).
