### ISSUE TITLE
Custom subdomain: technologies.langleyfoxall.co.uk

### ISSUE THREAD

**Issue by DivineOmega** [langleyfoxall/technologies#77]
### What you would like to change/add

We should create a custom subdomain for the technologies GitHub Pages site. This simply requires a new subdomain in the DNS zone (`technologies`) CNAMEd to `langleyfoxall.github.io`, and relevant configuration in the 'Settings' section of the repo.

### Why you would like to change/add this

This would make the technologies mini-site far easier to find and reference. It could also be linked from the main Langley Foxall site without going offsite.

### Sources

* https://help.github.com/articles/setting-up-a-custom-subdomain/
* https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/
* https://help.github.com/articles/custom-domain-redirects-for-github-pages-sites/

**Comment by wheatleyjj** [comment]
Completed. https://technologies.langleyfoxall.co.uk

**Comment by DivineOmega** [comment]
@wheatleyjj Nice!
