### ISSUE TITLE
Structuring of try blocks in php

### ISSUE THREAD

**Issue by AlexCatch** [langleyfoxall/technologies#79]
### What you would like to change/add
I propose we add a rule to our php standards to ensure that code that doesn't throw an exception stays out of the try block of a try/catch statement.

### Why you would like to change/add this

A try/catch statement has a fixed purpose, to catch exceptions and handle them. Having code that doesn't throw inside of the try block is redundant and unnecessary.

I feel like it could lead to confusion where a developer is led to believe a method call can throw when it doesn't because it's inside of a try block, leading to confusing code.

### Examples

This

```php
try {
	$supplier->update($request->validated());
    flash('Successfully updated supplier.')->success();
    return redirect()->route('suppliers.show', $supplier->id);
} catch (Exception $e) {
	flash('Failed to update supplier. Please try again later.')->error();
}
return redirect()->back();
```

becomes this

```php
try {
	$supplier->update($request->validated());
} catch (Exception $e) {
	flash('Failed to update supplier. Please try again later.')->error();
	return redirect()->back();
}
flash('Successfully updated supplier.')->success();
return redirect()->route('suppliers.show', $supplier->id);
```

I believe the second one makes more sense as `flash()` and `redirect()` do not throw exceptions so don't belong inside of the try loop.

### Checklist
- [x] I have checked that this is not a duplicate issue.

### Sources

* [Langley Foxall](https://langleyfoxall.co.uk) - The Langley Foxall website

**Comment by ash123456789** [comment]
A better example would be this:

```php
        try {
            $customer->update($request->validated());

            flash('Successfully updated customer.')->success();
        } catch (Exception $e) {
            flash('Failed to update customer. Please try again later.')->error();
        }

        return redirect()->back();
```

**Comment by AlexCatch** [comment]
`flash()` doesn't throw an exception so I don't feel should be inside of the try block
