### ISSUE TITLE
Scope of variables in PHP and where they should be declared

### ISSUE THREAD

**Issue by jaredkove** [langleyfoxall/technologies#83]
### What you would like to change/add
In most languages - you would be expected to declare the variable in the scope in which you'd like to reference/consume it in.

In PHP this isn't the case and you can declare variables deep inside an `if` statement, for example and reference it outside of that `if`.

I'd like to ask the question/suggest whether we should declare variables in the scope where they're to be consumed, for ease of reading.

### Examples
This works: 
```php
            if (true === false) {
                $user = null;
            } else {
                $user = User::find($request->user_id);
            }

           // I can use $user here
```

But I propose:
```php
            $user = null;
            if (true !== false)
                $user = User::find($request->user_id);
            }

           // I can use $user here
```

N.B The above code doesn't make sense for an number of reasons, but focus on the declaration aspect.

### Checklist
- [x] I have checked that this is not a duplicate issue.

**Comment by AlexCatch** [comment]
Declare variables in the outermost scope possible is usually my go to but also follow it logically.

**Comment by DivineOmega** [comment]
Definitely agreed, in all but the most unusual situation.

This also has the side effect of promoting smaller `if` blocks and the like.
