### ISSUE TITLE
Solidify of our git workflow

### ISSUE THREAD

**Issue by AlexCatch** [langleyfoxall/technologies#85]
### What you would like to change/add
We need to solidify our Git flow as we all seem to be using different standards for changes/fixes/features.

The most logical flow for me would be

- `develop` for the latest working copy of the code base
- `feature/*` for new or changes to features / sections
- `fix/*` for fixes into develop
- `staging/*` for the latest code on the staging server
- `production/*` for the latest code on the production server
- `hotfix/*` for emergency fixes into staging / production

I know there are different opinions on what to name what, the flow above closes matches what we've already got in the repo but adds `fixes/*` and updates the `master` branch to a more descriptive `develop` branch.

I know @ash123456789 has an idea for an `improvement/*` branch name so I think this issue is a good place to discuss the final flow we should adopt.

cc @ash123456789 @dextermb @MaxHarrisonGit @wheatleyjj @DivineOmega

### Checklist
- [x] I have checked that this is not a duplicate issue.

**Comment by ash123456789** [comment]
In my opinion this makes more sense. I've changed my mind on the name of the branch so instead of `improvement/*` it should be `fix/*` to keep it short and simple.

#### Base
* `master` for the latest working copy of the code base.
* `staging` for the latest code on the staging server (usually workshop).
* `production` for the latest code on the production server.

#### Additional
* `feature/*` for new features.
* `fix/*` for fixes to existing features.
* `hotfix/*` for emergency fixes into staging or production.

**Comment by dextermb** [comment]
> > In my opinion this makes more sense. I've changed my mind on the name of the branch so instead of `improvement/*` it should be `fix/*` to keep it short and simple.
> > #### Base
> > 
> > * `master` for the latest working copy of the code base.
> > * `staging` for the latest code on the staging server (usually workshop).
> > * `production` for the latest code on the production server.
> > 
> > #### Additional
> > 
> > * `feature/*` for new features.
> > * `fix/*` for fixes to existing features.
> > * `hotfix/*` for emergency fixes into staging or production.
> 
> What is your opinion on not having `hotfix/*` into staging. I think this because if the project is not yet on production and the client is not desperate for the fix and/or losing them money i feel like this should go through master and therefore would be a fix. Thoughts?

I believe `hotfix/*` should be able to go into staging. If there's a breaking push on the server, then it's sometimes quickier to just push a temporary fix until time is made to resolve it properly.

**Comment by JacobBrassington** [comment]
I take it that this should then also be merged into master as well to keep all the branches synced. Am I understanding that right?

**Comment by dextermb** [comment]
> I take it that this should then also be merged into master as well to keep all the branches synced. Am I understanding that right?

Yup, if we were to follow conventional hotfix patterns

**Comment by ash123456789** [comment]
> > In my opinion this makes more sense. I've changed my mind on the name of the branch so instead of `improvement/*` it should be `fix/*` to keep it short and simple.
> > #### Base
> > 
> > * `master` for the latest working copy of the code base.
> > * `staging` for the latest code on the staging server (usually workshop).
> > * `production` for the latest code on the production server.
> > 
> > #### Additional
> > 
> > * `feature/*` for new features.
> > * `fix/*` for fixes to existing features.
> > * `hotfix/*` for emergency fixes into staging or production.
> 
> What is your opinion on not having `hotfix/*` into staging. I think this because if the project is not yet on production and the client is not desperate for the fix and/or losing them money i feel like this should go through master and therefore would be a fix. Thoughts?

The hotfix should ideally always go through staging just in case something has been missed while testing the hotfix which could, for what ever reason, cause serious issues and cause data corruption/loss issues.

**Comment by AlexCatch** [comment]
I feel like a `hotfix/*` can still go into production.

Before being deployed Travis will run all your tests which, if you've got good tests, ensure that the code you've introduced doesn't break anything.

I feel by having a rule to only allow hotfixes into production, you're bypassing the benefits of Travis which is there to ensure that only working code goes into production.

**Comment by dextermb** [comment]
> I feel like a `hotfix/*` can still go into production.

@AlexCatch, We're not saying that `hotfix/*` doesn't. We were just responding to what Jacob said 👍

**Comment by AlexCatch** [comment]
@dextermb It was a reply to Ash's comment above mine

**Comment by DivineOmega** [comment]
Regarding hotfixes going directly into production I agree with both @ash123456789 and @AlexCatch.

> The hotfix should ideally always go through staging

I believe the above the should be our standard practice.

However, I believe this should be overridable in extreme circumstances, such as complete system outage. In the case that this may cause serious issues / data loss, this should be first confirmed by the client.

**Comment by AlexCatch** [comment]
@DivineOmega I agree, pretty much all code changes should go to staging for manual QA before being deployed, Travis running tests before deploying to production is essentially a final quality check & safety measure.

**Comment by DivineOmega** [comment]
I agree with both @AlexCatch and @ash123456789's general proposals regarding git flow, including the addition of a `fix/*` branch.

The main difference now is opinions regarding what to call the unstable branch, either master or develop. I shall create another Git issue to vote on this, and it will appear referenced below..

**Comment by DivineOmega** [comment]
> @DivineOmega I agree, pretty much all code changes should go to staging for manual QA before being deployed, Travis running tests before deploying to production is essentially a final quality check & safety measure.

Agreed! 👍
